[package]
name = "ot"
version = "0.1.0"
authors = ["pandaman <kointosudesuyo@infoseek.jp>"]

[dependencies]
futures = "0.2.0-alpha"
futures-util = "0.2.0-alpha"

serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
rand = "0.4"
